fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    gpg_key:
      repo: git://github.com/treydock/puppet-gpg_key.git
  symlinks:
    repo_centos: "#{source_dir}"
